### ISSUE TITLE
error when install the plugins

### ISSUE THREAD

**Issue by Yudhistir4** [ozguryazilimas/redmine_default_assignee#3]
![image](https://user-images.githubusercontent.com/42562037/47779403-994b9600-dd2b-11e8-8aa3-7b8e15ac898d.png)
this happen when i try to install this plugin in windows

**Comment by zaburt** [comment]
According to the log bundler is not able to access C:/Bitnami/redmine-3.4.6-3/apps/redmine/htdocs/.bundle/config file. Are you getting this error when starting Redmine or running bundle install ? Did you install Redmine as an administrator user, but running Redmine or "bundle install" as a regular user ?

This does not seem to be related to this plugin as it does not have a Gemfile, so bundler does not use it.

**Comment by Yudhistir4** [comment]
![image](https://user-images.githubusercontent.com/42562037/47833075-8d171580-ddcb-11e8-8f58-e631069dd803.png)
hi zaburt,

i have try to install again and show this word, any idea to solve this one?

**Comment by zaburt** [comment]
The output on https://github.com/ozguryazilimas/redmine_default_assignee/issues/3#issuecomment-434929282 is not an error, it means bundle install for production mode is successful.

This issue is not related to Redmine Default Assignee plugin, but rather related to installation of Redmine through Bitnami. Please refer to their documentation and communication channels.
